site_name: nino
copyright: "© 2021 ninteru, licensed under Creative Commons CC BY-SA 4.0"
repo_url: "https://github.com/ninteru/ninteru.github.io"
nav:
    - home: index.md
    - links: links.md
theme:
    name: null
    custom_dir: 'ninteru_mkdocs_theme/ninteru_mkdocs_theme'